<%@include file="./shared/header.jsp"%>

<c:if test="${isAdmin == true}">
	<li><a href="category">Category</a></li>
	<li><a href="supplier">Supplier</a></li>
</c:if>
<div class="container">

	<br>
	<div id="myCarousel" class="carousel slide" data-ride="carousel">

		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1"></li>
			<li data-target="#myCarousel" data-slide-to="2"></li>
			<li data-target="#myCarousel" data-slide-to="3"></li>
		</ol>

		<div class="carousel-inner" role="listbox">

			<div class="item active">
				<img src="resources/Images/electric.gif" alt="Image1">
				<div class="carousel-caption">
					<h3>Electric Guitar</h3>
				</div>
			</div>

			<div class="item">
				<img src="resources/Images/guitar (1).jpg" alt="Image2">
				<div class="carousel-caption">
					<h3>Acoustic Guitar</h3>
				</div>
			</div>

			<div class="item">
				<img src="resources/Images/guitar (3).jpg" alt="Image3">
				<div class="carousel-caption">
					<h3>Ukulele beside an acoustic</h3>
				</div>
			</div>

			<div class="item">
				<img src="resources/Images/acoustic.gif" alt="Image4">
				<div class="carousel-caption">
					<h3>Strumming</h3>
				</div>
			</div>

		</div>

		<a class="left carousel-control" href="#myCarousel" role="button"
			data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"
			aria-hidden="true"></span> <span class="sr-only">Previous</span>
		</a> <a class="right carousel-control" href="#myCarousel" role="button"
			data-slide="next"> <span
			class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>

	</div>
</div>

<div class="row">
	<div class="col-sm-4">
		<a href="acoustic.html"> <img class="category"
			src="resources/Images/acoustic.png"> <span class="text-content"><span>
					<h3>Acoustic</h3> The steel-string acoustic guitar is a modern form
					of guitar that descends from the classical guitar, but is strung
					with steel strings for a brighter, louder sound. It is often
					referred to simply as an acoustic guitar, though the nylon-strung
					classical guitar is also sometimes called an acoustic guitar.
			</span></span>
		</a>
	</div>
	<div class="col-sm-4">
		<a href="acoustic.html"> <img class="category"
			src="resources/Images/electric.png"> <span class="text-content"><span>
					<h3>Electric</h3> An electric guitar is a guitar that uses a pickup
					to convert the vibration of its strings which are typically made of
					metal, and which occurs when a guitarist strums, plucks or
					fingerpicks the strings into electrical impulses. The vibrations of
					the strings are sensed by a pickup, of which the most common type
					is the magnetic pickup, which uses the principle of direct
					electromagnetic induction. The signal generated by an electric
					guitar is too weak to drive a loudspeaker, so it is plugged into a
					guitar amplifier before being sent to a loudspeaker, which makes a
					sound loud enough to hear. The output of an electric guitar is an
					electric signal, and the signal can easily be altered by electronic
					circuits to add "color" to the sound or change the sound. Often the
					signal is modified using effects such as reverb and distortion and
					"overdrive", with the latter being a key element of the sound of
					the electric guitar as it is used in blues and rock music.
			</span></span>
		</a>
	</div>
	<div class="col-sm-4">
		<a href="acoustic.html"> <img class="category"
			src="resources/Images/ukulele.jpg"> <span class="text-content"><span>
					<h3>Ukulele</h3> The ukulele,sometimes abbreviated to uke, is a
					member of the lute family of instruments; it generally employs four
					nylon or gut strings or four courses of strings.
			</span></span>
		</a>
	</div>
</div>

